# -*- coding: utf-8 -*-
"""Projeto Individual

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBNN5VWpR9QRRn_yV9ykWTPpqZbdsy69

## Projeto individual
*Aqui sera dado inicio ao trabalho individual, onde sera respondidos as questões da mesma.*

Aqui estou realizando a importação dos dados que seram realizado as analises.
"""

import pandas as pd

Rel_prog = pd.read_excel("/content/drive/MyDrive/Data Analitic/Modulo 03/Projeto Individual/dados_devs.xlsx")
Rel_prog

"""### Total e a media de Horas Trabalhadas

*Aqui irei realizar as analises dos horarios totais e medias de trabalho.*
"""

# Calcular o total de horas trabalhadas
total_horas_trabalhadas = Rel_prog['Horas Trabalhadas'].sum()
print(f'Total de horas trabalhadas: {total_horas_trabalhadas}')

# Calcular a media de horas trabalhadas
total_horas_trabalhadas = Rel_prog['Horas Trabalhadas'].mean()
print(f'Total de horas trabalhadas: {total_horas_trabalhadas}')

"""### Total e media de Bugs Corigidos
*Aqui irei realizar as analises dos Bugs totais e medias corrigidos.*
"""

# Calcular total de Bugs Corrigido
total_bug_corrigido = Rel_prog['Bugs Corrigidos'].mean()
print(f'Total de horas trabalhadas: {total_bug_corrigido}')

# Calcular a media de Bugs Corrigido
total_bug_corrigido = Rel_prog['Bugs Corrigidos'].sum()
print(f'Total de horas trabalhadas: {total_bug_corrigido}')

"""### Totoal e media de tarefas concluidas

*Aqui eu irei realizar as analises de toal e mesdia das tarefas concluídas*
"""

# Calcular total de tarefas concluidas
total_tarefa_concluida = Rel_prog['Tarefas Concluidas'].sum()
print(f'Total de horas trabalhadas: {total_tarefa_concluida}')

# Calcular da media  de tarefas concluidas
total_tarefa_concluida = Rel_prog['Tarefas Concluidas'].mean()
print(f'Total de horas trabalhadas: {total_tarefa_concluida}')

"""### Produtividade Diária (Tarefas Concluídas por Hora)

*Conclusão, produtividade por serviço.*
"""

# Dados da tabela
horas_trabalhadas = [6, 7, 8, 6, 7, 5, 4]
tarefas_concluidas = [5, 4, 6, 4, 5, 3, 2]

# Calcular produtividade diária (tarefas concluídas por hora)
produtividade_diaria = [tc / ht for tc, ht in zip(tarefas_concluidas, horas_trabalhadas)]

# Imprimir resultados
for dia, prod in enumerate(produtividade_diaria, start=1):
    print(f"Produtividade no dia {dia}: {prod:.2f} tarefas/hora")